spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boke?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 761121532
  jpa:
    database: mysql
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3000

server:
  port: 10010
mybatis:
  type-aliases-package: com.example.web.Entity
  mapper-locations: classpath:mapper/*.xml

application:
  version: 1.0.0
  profile: D:/profile/

